// Startvoorraad voor het commando-woordenboek.
//
// Doel: iemand die de app voor het eerst opent heeft meteen iets om in te
// zoeken, in plaats van een leeg scherm dat pas na weken gebruik nuttig wordt.
//
// Drie kenmerken:
//   - gewone commando's, die je kunt uitvoeren
//   - fragmenten (`snippet: true`), die alleen ergens ín een bat-bestand horen.
//     Die krijgen geen uitvoerknop, want los draaien slaat nergens op.
//   - ingrijpende commando's (`danger: true`), die schijven wissen, rechten
//     omzetten of het systeem herstarten. Die vragen eerst om bevestiging.
//   - sjablonen (`template: true`), waar je eerst een naam, pad of nummer in
//     moet vullen. Ook commando's die om invoer vragen of alleen zin hebben in
//     een eigen venster. Die krijgen geen uitvoerknop: zo draaien levert niets
//     op. Pas je de tekst aan, dan komen de knoppen vanzelf terug.
//
// Uitbreiden mag gerust: een regel toevoegen is genoeg, de app doet de rest.

const BUILTIN_COMMANDS = [
  // ── Navigeren en bestanden ────────────────────────────────────────────────
  { cmd: 'dir', label: 'Bestanden in deze map', tags: ['bestanden'],
    note: 'Voeg /a toe voor verborgen bestanden, /o-d om op datum te sorteren (nieuwste eerst).' },
  { cmd: 'dir /s /b', label: 'Alle bestanden onder deze map', tags: ['bestanden'],
    note: 'Kale lijst met volledige paden, ook uit onderliggende mappen. Handig om door te sluizen naar findstr.' },
  { cmd: 'cd ..', label: 'Een map omhoog', tags: ['bestanden'] },
  { cmd: 'cd /d D:\\werk', label: 'Naar een map op een andere schijf', tags: ['bestanden'], template: true,
    note: 'Zonder /d wisselt cd wel de map maar niet de schijf — een klassieke valkuil.' },
  { cmd: 'tree /f', label: 'Mappenboom met bestanden', tags: ['bestanden'] },
  { cmd: 'type bestand.txt', label: 'Inhoud van een bestand tonen', tags: ['bestanden'], template: true },
  { cmd: 'mkdir "nieuwe map"', label: 'Map aanmaken', tags: ['bestanden'], template: true,
    note: 'Maakt ook tussenliggende mappen aan: mkdir a\\b\\c werkt in één keer.' },
  { cmd: 'copy bron.txt doel.txt', label: 'Bestand kopiëren', tags: ['bestanden'], template: true },
  { cmd: 'xcopy /s /e /i /y "bron" "doel"', label: 'Map kopiëren met inhoud', tags: ['bestanden'], template: true,
    note: '/s en /e nemen submappen mee (ook lege), /i gaat uit van een map, /y vraagt niet om bevestiging.' },
  { cmd: 'robocopy "bron" "doel" /mir', label: 'Map spiegelen', tags: ['bestanden'], template: true, danger: true,
    note: 'Let op: /mir verwijdert in het doel alles wat niet in de bron staat. Test eerst met /l (alleen tonen).' },
  { cmd: 'move oud.txt nieuw.txt', label: 'Verplaatsen of hernoemen', tags: ['bestanden'], template: true },
  { cmd: 'ren oud.txt nieuw.txt', label: 'Hernoemen', tags: ['bestanden'], template: true },
  { cmd: 'del /f /q bestand.txt', label: 'Bestand verwijderen', tags: ['bestanden'], template: true,
    note: '/f forceert ook alleen-lezen bestanden, /q vraagt niets. Gaat niet naar de prullenbak.' },
  { cmd: 'rmdir /s /q "map"', label: 'Map met inhoud verwijderen', tags: ['bestanden'], template: true, danger: true,
    note: 'Onherroepelijk — er komt geen bevestiging en niets belandt in de prullenbak.' },
  { cmd: 'findstr /s /i /n "zoekterm" *.txt', label: 'Zoeken in bestanden', tags: ['zoeken'], template: true,
    note: '/s doorzoekt submappen, /i negeert hoofdletters, /n toont regelnummers.' },
  { cmd: 'where programma', label: 'Waar staat dit programma?', tags: ['zoeken'], template: true,
    note: 'Zoekt in PATH. Handig als een commando "wordt niet herkend" of als je twee versies vermoedt.' },
  { cmd: 'fc bestand1.txt bestand2.txt', label: 'Twee bestanden vergelijken', tags: ['bestanden'], template: true },
  { cmd: 'attrib -r -h -s bestand.txt', label: 'Alleen-lezen, verborgen en systeem weghalen', tags: ['bestanden'], template: true },

  // ── Processen en systeem ──────────────────────────────────────────────────
  { cmd: 'tasklist', label: 'Draaiende processen', tags: ['systeem'] },
  { cmd: 'tasklist | findstr /i chrome', label: 'Zoeken in draaiende processen', tags: ['systeem'] },
  { cmd: 'taskkill /f /im programma.exe', label: 'Programma geforceerd afsluiten', tags: ['systeem'], template: true,
    note: 'Voeg /t toe om ook de onderliggende processen mee te nemen.' },
  { cmd: 'taskkill /f /pid 1234', label: 'Proces afsluiten op proces-id', tags: ['systeem'], template: true },
  { cmd: 'systeminfo', label: 'Systeemgegevens', tags: ['systeem'],
    note: 'Duurt een paar seconden. Toont onder meer Windows-versie, geheugen en installatiedatum.' },
  { cmd: 'shutdown /r /t 0', label: 'Nu opnieuw opstarten', tags: ['systeem'], danger: true,
    note: '/s in plaats van /r sluit af. Bedacht je je? shutdown /a breekt een geplande afsluiting af.' },
  { cmd: 'sfc /scannow', label: 'Systeembestanden controleren en herstellen', tags: ['systeem'],
    note: 'Vereist beheerdersrechten en duurt een tijd.' },
  { cmd: 'chkdsk C: /f', label: 'Schijf controleren', tags: ['systeem'], template: true,
    note: 'Op de systeemschijf gebeurt dit pas bij de volgende herstart.' },
  { cmd: 'powercfg /batteryreport', label: 'Accurapport maken', tags: ['systeem'] },
  { cmd: 'net session >nul 2>&1', label: 'Controleren op beheerdersrechten', tags: ['systeem', 'bat'],
    note: 'Levert errorlevel 1 op als je géén beheerder bent. De gebruikelijke manier om dat in een script te toetsen.' },

  // ── Netwerk ───────────────────────────────────────────────────────────────
  { cmd: 'ipconfig /all', label: 'Alle netwerkinstellingen', tags: ['netwerk'] },
  { cmd: 'ipconfig /flushdns', label: 'DNS-cache legen', tags: ['netwerk'],
    note: 'Eerste ding om te proberen als een adres naar de verkeerde server wijst.' },
  { cmd: 'ipconfig /release', label: 'IP-adres vrijgeven', tags: ['netwerk'] },
  { cmd: 'ipconfig /renew', label: 'Nieuw IP-adres opvragen', tags: ['netwerk'] },
  { cmd: 'ping -n 4 google.com', label: 'Verbinding testen', tags: ['netwerk'],
    note: '-t blijft doorpingen tot je Ctrl+C drukt.' },
  { cmd: 'tracert google.com', label: 'Route naar een server volgen', tags: ['netwerk'] },
  { cmd: 'nslookup domein.nl', label: 'DNS-gegevens opvragen', tags: ['netwerk'], template: true },
  { cmd: 'netstat -ano', label: 'Open verbindingen met proces-id', tags: ['netwerk'],
    note: 'Zoek de poort, pak het pid uit de laatste kolom en zoek dat op met tasklist.' },
  { cmd: 'netstat -ano | findstr :8080', label: 'Wie gebruikt deze poort?', tags: ['netwerk'],
    note: 'Onmisbaar als een server niet wil starten omdat de poort bezet is.' },
  { cmd: 'netsh winsock reset', label: 'Netwerkstack herstellen', tags: ['netwerk'],
    note: 'Vereist beheerdersrechten en een herstart. Laatste redmiddel bij vage netwerkproblemen.' },
  { cmd: 'netsh wlan show profiles', label: 'Opgeslagen wifi-netwerken', tags: ['netwerk'] },

  // ── Handig in de prompt ───────────────────────────────────────────────────
  { cmd: 'cls', label: 'Scherm leegmaken', tags: ['prompt'] },
  { cmd: 'dir | clip', label: 'Uitvoer naar het klembord', tags: ['prompt'],
    note: 'Zet achter elk commando | clip om het resultaat te kunnen plakken.' },
  { cmd: 'echo %PATH%', label: 'PATH tonen', tags: ['prompt'] },
  { cmd: 'set', label: 'Alle omgevingsvariabelen', tags: ['prompt'] },
  { cmd: 'assoc .txt', label: 'Welk type hoort bij deze extensie?', tags: ['prompt'] },
  { cmd: 'ftype txtfile', label: 'Welk programma opent dit type?', tags: ['prompt'], template: true },
  { cmd: 'start .', label: 'Deze map openen in de verkenner', tags: ['prompt'] },
  { cmd: 'start "" "C:\\pad\\naar\\programma.exe"', label: 'Programma starten', tags: ['prompt', 'bat'], template: true,
    note: 'De lege "" is de venstertitel. Zonder die haakjes ziet start je pad aan voor de titel als er spaties in zitten.' },

  // ── Bouwstenen voor bat-bestanden ─────────────────────────────────────────
  { cmd: '@echo off', label: 'Commando\'s niet meeprinten', tags: ['bat'], snippet: true,
    note: 'Eerste regel van vrijwel elk bat-bestand. De @ zorgt dat deze regel zichzelf ook niet toont.' },
  { cmd: 'setlocal enabledelayedexpansion', label: 'Variabelen binnen een lus laten werken', tags: ['bat'], snippet: true,
    note: 'Zonder dit wordt %VAR% binnen een blok één keer ingevuld en verandert hij niet meer. Gebruik daarna !VAR! in plaats van %VAR%.' },
  { cmd: 'pause', label: 'Wachten op een toetsaanslag', tags: ['bat'], snippet: true,
    note: 'Zet dit aan het eind, anders klapt het venster dicht voordat je de uitvoer kunt lezen.' },
  { cmd: 'timeout /t 5 /nobreak >nul', label: 'Vijf seconden wachten', tags: ['bat'], snippet: true,
    note: '/nobreak negeert toetsaanslagen, >nul verbergt het aftellen.' },
  { cmd: 'if errorlevel 1 goto mislukt', label: 'Stoppen als het vorige commando faalde', tags: ['bat'], snippet: true,
    note: 'Let op: "errorlevel 1" betekent 1 of hoger. Voor precies 1 gebruik je if %errorlevel%==1.' },
  { cmd: 'if exist "bestand.txt" (\r\n  echo gevonden\r\n) else (\r\n  echo niet gevonden\r\n)', label: 'Bestaat dit bestand?', tags: ['bat'], snippet: true,
    note: 'Voor een map zet je er een backslash achter: if exist "map\\".' },
  { cmd: 'for %%f in (*.txt) do echo %%f', label: 'Lus over bestanden', tags: ['bat'], snippet: true,
    note: 'In een bat-bestand dubbele procenttekens (%%f); typ je het rechtstreeks in de prompt, dan enkele (%f).' },
  { cmd: 'for /r %%f in (*.log) do del "%%f"', label: 'Lus door alle submappen', tags: ['bat'], snippet: true },
  { cmd: 'for /f "tokens=*" %%a in (\'dir /b\') do echo %%a', label: 'Lus over de uitvoer van een commando', tags: ['bat'], snippet: true },
  { cmd: 'set "NAAM=waarde"', label: 'Variabele zetten', tags: ['bat'], snippet: true,
    note: 'De aanhalingstekens om het geheel voorkomen dat een spatie na de waarde meekomt.' },
  { cmd: 'set /p ANTWOORD=Doorgaan? ', label: 'Iets aan de gebruiker vragen', tags: ['bat'], snippet: true },
  { cmd: 'call ander-script.bat', label: 'Ander bat-bestand aanroepen', tags: ['bat'], snippet: true,
    note: 'Zonder call komt de besturing nooit terug en stopt jouw script zodra het andere klaar is.' },
  { cmd: 'cd /d "%~dp0"', label: 'Naar de map van dit script', tags: ['bat'], snippet: true,
    note: '%~dp0 is de map waarin het bat-bestand staat, inclusief afsluitende backslash. Zo werkt je script ook als het ergens anders vandaan gestart wordt.' },
  { cmd: 'echo %date% %time%', label: 'Datum en tijd', tags: ['bat'], snippet: true },
  { cmd: 'echo Fout: %errorlevel%', label: 'Foutcode van het vorige commando', tags: ['bat'], snippet: true },
  { cmd: 'commando >nul 2>&1', label: 'Uitvoer en fouten wegslikken', tags: ['bat'], snippet: true,
    note: '>nul verbergt de gewone uitvoer, 2>&1 stuurt ook de foutmeldingen daarheen.' },
  { cmd: 'commando >> "log.txt" 2>&1', label: 'Uitvoer naar een logbestand', tags: ['bat'], snippet: true,
    note: 'Met >> plak je aan het bestand vast; met één > overschrijf je het elke keer.' },
  { cmd: 'exit /b 1', label: 'Script stoppen met een foutcode', tags: ['bat'], snippet: true,
    note: 'Met /b stopt alleen het script; zonder /b sluit het hele cmd-venster.' },
  { cmd: 'goto :eof', label: 'Naar het einde springen', tags: ['bat'], snippet: true },
  { cmd: 'rem Dit is commentaar', label: 'Commentaarregel', tags: ['bat'], snippet: true,
    note: ':: werkt ook en typt korter, maar gaat mis binnen haakjes van een if- of for-blok. rem is altijd veilig.' },
  { cmd: 'title Mijn script', label: 'Titel van het venster', tags: ['bat'], snippet: true },
  { cmd: 'powershell -NoProfile -Command "Start-Process -FilePath \'%~f0\' -Verb RunAs"', label: 'Zichzelf herstarten als beheerder', tags: ['bat'], snippet: true,
    note: 'Combineer met net session om alleen te herstarten als het nog nodig is.' },
  // ── Hulp en versie ────────────────────────────────────────────────────────
  { cmd: 'help', label: 'Lijst van ingebouwde commando\'s', tags: ['prompt'],
    note: 'Toont alleen de commando\'s die in cmd zelf zitten. Voor uitleg over één ervan: help dir.' },
  { cmd: 'dir /?', label: 'Uitleg bij een commando', tags: ['prompt'],
    note: 'De /? achter vrijwel elk commando toont de mogelijke schakelaars. Werkt ook bij programma\'s die niet van Windows zijn.' },
  { cmd: 'ver', label: 'Windows-versie', tags: ['systeem'],
    note: 'Kort en snel. Wil je het buildnummer en meer, gebruik dan systeminfo of winver.' },
  { cmd: 'winver', label: 'Versievenster van Windows', tags: ['systeem'],
    note: 'Opent een klein venster met versie en buildnummer — handiger om te kopiëren dan ver.' },
  { cmd: 'hostname', label: 'Naam van deze computer', tags: ['systeem'] },
  { cmd: 'whoami', label: 'Onder welke gebruiker draai ik?', tags: ['systeem'],
    note: 'whoami /groups laat ook zien of je in de beheerdersgroep zit.' },
  { cmd: 'echo Hallo wereld', label: 'Tekst tonen', tags: ['prompt'],
    note: 'Zonder tekst toont echo of het meeprinten van commando\'s aan of uit staat. Een lege regel maak je met echo. (met punt, zonder spatie).' },
  { cmd: 'echo. > leeg.txt', label: 'Leeg bestand maken', tags: ['bestanden'], template: true,
    note: 'De punt direct achter echo geeft een lege regel; met > maak je daar een bestand van.' },

  // ── Afsluiten en aanmelden ────────────────────────────────────────────────
  { cmd: 'logoff', label: 'Huidige gebruiker afmelden', tags: ['systeem'], danger: true,
    note: 'Sluit je sessie meteen af — niet-opgeslagen werk gaat verloren. Voor een andere sessie: logoff <sessie-id>, op te zoeken met query session.' },
  { cmd: 'shutdown /s /t 60 /c "Over een minuut"', label: 'Afsluiten met uitstel en melding', tags: ['systeem'], danger: true,
    note: '/t is het aantal seconden, /c de tekst die de gebruiker ziet. Bedacht je je? shutdown /a breekt het af.' },
  { cmd: 'shutdown /a', label: 'Geplande afsluiting afbreken', tags: ['systeem'],
    note: 'Werkt alleen zolang de teller nog loopt.' },
  { cmd: 'shutdown /h', label: 'Slaapstand', tags: ['systeem'],
    note: 'Alleen als de slaapstand aan staat; inschakelen kan met powercfg /hibernate on.' },

  // ── Processen en diensten ─────────────────────────────────────────────────
  { cmd: 'tasklist /svc', label: 'Processen met de diensten die erin draaien', tags: ['systeem'],
    note: 'Handig om te zien welke dienst in welke svchost.exe zit.' },
  { cmd: 'tasklist /fi "memusage gt 500000"', label: 'Processen die veel geheugen gebruiken', tags: ['systeem'],
    note: 'De waarde is in kilobytes; dit toont alles boven ongeveer 500 MB.' },
  { cmd: 'sc query', label: 'Alle draaiende diensten', tags: ['systeem'],
    note: 'Voor één dienst: sc query wuauserv. sc qc <naam> toont de instellingen.' },
  { cmd: 'net stop "Naam van dienst"', label: 'Dienst stoppen', tags: ['systeem'], template: true, danger: true,
    note: 'Vereist beheerdersrechten. Starten gaat met net start.' },
  { cmd: 'schtasks /query /fo table', label: 'Geplande taken', tags: ['systeem'],
    note: 'Voeg /v toe voor alle details, of gebruik /create om er zelf een te maken.' },
  { cmd: 'driverquery', label: 'Geïnstalleerde stuurprogramma\'s', tags: ['systeem'] },

  // ── Schijven ──────────────────────────────────────────────────────────────
  { cmd: 'wmic logicaldisk get name,size,freespace', label: 'Vrije ruimte per schijf', tags: ['systeem'],
    note: 'Op nieuwere Windows-versies is wmic weggehaald; dan werkt: fsutil volume diskfree C:' },
  { cmd: 'fsutil volume diskfree C:', label: 'Vrije ruimte op een schijf', tags: ['systeem'],
    note: 'De opvolger van de wmic-variant en overal aanwezig.' },
  { cmd: 'diskpart', label: 'Schijfbeheer op de opdrachtregel', tags: ['systeem'], template: true, danger: true,
    note: 'Opent een eigen prompt waarin je partities kunt maken en wissen. Eén verkeerde "select disk" en je bent de verkeerde schijf kwijt. Begin altijd met list disk en controleer de grootte voordat je iets selecteert.' },
  { cmd: 'format D: /fs:ntfs /q', label: 'Schijf formatteren', tags: ['systeem'], template: true, danger: true,
    note: 'Wist álles op die letter. /q is snelformatteren, /fs kiest het bestandssysteem. Controleer de schijfletter twee keer — dit is niet terug te draaien.' },
  { cmd: 'chkdsk C: /f /r', label: 'Schijf controleren en sectoren herstellen', tags: ['systeem'], template: true,
    note: '/r zoekt ook naar slechte sectoren en duurt lang. Op de systeemschijf gebeurt het bij de volgende herstart.' },
  { cmd: 'defrag C: /o', label: 'Schijf optimaliseren', tags: ['systeem'],
    note: '/o kiest zelf de juiste aanpak: defragmenteren bij een harde schijf, TRIM bij een SSD.' },
  { cmd: 'mountvol', label: 'Koppelpunten en schijf-ID\'s', tags: ['systeem'] },

  // ── Herstel ───────────────────────────────────────────────────────────────
  { cmd: 'DISM /Online /Cleanup-Image /RestoreHealth', label: 'Windows-installatiekopie herstellen', tags: ['systeem'],
    note: 'Draai dit vóór sfc /scannow als die klaagt dat hij iets niet kan repareren. Vereist beheerdersrechten en internet.' },
  { cmd: 'gpupdate /force', label: 'Groepsbeleid opnieuw toepassen', tags: ['systeem'] },
  { cmd: 'cleanmgr', label: 'Schijfopruiming openen', tags: ['systeem'] },

  // ── Rechten en eigendom ───────────────────────────────────────────────────
  { cmd: 'takeown /f "C:\\pad\\map" /r /d j', label: 'Eigenaar worden van bestanden', tags: ['systeem'], template: true, danger: true,
    note: '/r doet ook submappen, /d j beantwoordt de vragen met ja. Gebruik dit alleen op mappen die je zelf beheert — op systeemmappen kun je Windows ermee slopen.' },
  { cmd: 'icacls "C:\\pad" /grant Gebruikers:F', label: 'Rechten toekennen', tags: ['systeem'], template: true, danger: true,
    note: 'F is volledig beheer, M wijzigen, R alleen lezen. Meestal het vervolg op takeown.' },
  { cmd: 'runas /user:Administrator cmd', label: 'Iets als andere gebruiker starten', tags: ['systeem'], template: true,
    note: 'Vraagt om het wachtwoord van die gebruiker. Let op: dit is niet hetzelfde als "als administrator uitvoeren".' },

  // ── Netwerk, aanvullend ───────────────────────────────────────────────────
  { cmd: 'getmac /v', label: 'MAC-adressen van je netwerkkaarten', tags: ['netwerk'] },
  { cmd: 'arp -a', label: 'Wie is er nog meer op dit netwerk?', tags: ['netwerk'],
    note: 'Toont de gekoppelde IP- en MAC-adressen die je computer recent heeft gezien.' },
  { cmd: 'route print', label: 'Routetabel', tags: ['netwerk'] },
  { cmd: 'netsh int ip reset', label: 'TCP/IP-instellingen herstellen', tags: ['netwerk'], danger: true,
    note: 'Zet je netwerkinstellingen terug naar de standaard. Vereist beheerdersrechten en een herstart. Vaste IP-adressen ben je daarna kwijt.' },
  { cmd: 'netsh wlan show profile naam=Wifinaam key=clear', label: 'Wifi-wachtwoord terugvinden', tags: ['netwerk'], template: true,
    note: 'Het wachtwoord staat onder "Sleutelinhoud". Werkt alleen voor netwerken die op deze computer zijn opgeslagen.' },
  { cmd: 'netsh interface show interface', label: 'Netwerkadapters en hun status', tags: ['netwerk'] },
  { cmd: 'net use', label: 'Gekoppelde netwerkschijven', tags: ['netwerk'],
    note: 'Koppelen: net use Z: \\\\server\\map. Loskoppelen: net use Z: /delete.' },
  { cmd: 'net user', label: 'Gebruikers op deze computer', tags: ['systeem'],
    note: 'net user <naam> toont de details van één gebruiker, inclusief de groepen waar die in zit.' },
  { cmd: 'curl -I https://example.com', label: 'Alleen de kopregels van een webadres ophalen', tags: ['netwerk'],
    note: 'curl zit sinds Windows 10 standaard in Windows. Handig om te zien of een server reageert en welke statuscode hij geeft.' },
  { cmd: 'ping -t 8.8.8.8', label: 'Blijven pingen', tags: ['netwerk'],
    note: 'Loopt door tot je Ctrl+C drukt. Goed om een verbinding een tijd in de gaten te houden.' },

  // ── Vensters en programma\'s openen ───────────────────────────────────────
  { cmd: 'explorer .', label: 'Deze map openen in de verkenner', tags: ['prompt'] },
  { cmd: 'control', label: 'Configuratiescherm openen', tags: ['prompt'],
    note: 'Rechtstreeks naar een onderdeel kan ook: appwiz.cpl voor programma\'s, ncpa.cpl voor netwerkverbindingen, sysdm.cpl voor systeemeigenschappen.' },
  { cmd: 'msinfo32', label: 'Systeeminformatie in een venster', tags: ['systeem'] },
  { cmd: 'dxdiag', label: 'DirectX- en grafische gegevens', tags: ['systeem'] },
  { cmd: 'resmon', label: 'Broncontrole openen', tags: ['systeem'],
    note: 'Laat per proces zien wat het aan schijf, netwerk en geheugen doet — meer detail dan taakbeheer.' },
  { cmd: 'regedit', label: 'Register-editor', tags: ['systeem'], danger: true,
    note: 'Verkeerde wijzigingen kunnen Windows onstartbaar maken. Exporteer eerst de sleutel die je aanpast.' },
  { cmd: 'reg query "HKCU\\Software" /s /f zoekterm', label: 'Zoeken in het register', tags: ['systeem'], template: true,
    note: 'Alleen lezen, dus veilig. /s doorzoekt onderliggende sleutels, /f is de zoekterm.' },

  // ── Overig handig ─────────────────────────────────────────────────────────
  { cmd: 'certutil -hashfile bestand.zip SHA256', label: 'Controlegetal van een bestand', tags: ['bestanden'], template: true,
    note: 'Om te controleren of een download klopt. Vergelijk de uitkomst met wat de maker opgeeft.' },
  { cmd: 'tar -xf archief.zip', label: 'Archief uitpakken', tags: ['bestanden'], template: true,
    note: 'tar zit sinds Windows 10 standaard in Windows en kan ook met zip overweg. Inpakken: tar -cf archief.zip map' },
  { cmd: 'mklink /d "snelkoppeling" "C:\\echte\\map"', label: 'Maplink maken', tags: ['bestanden'], template: true,
    note: 'Gedraagt zich als een echte map maar wijst naar een andere plek. Vereist beheerdersrechten; laat /d weg voor een bestand.' },
  { cmd: 'compact /c /s "C:\\map"', label: 'Map comprimeren op schijf', tags: ['bestanden'], template: true,
    note: '/u in plaats van /c maakt het weer ongedaan.' },
  { cmd: 'cipher /w:C:\\', label: 'Vrije ruimte onherstelbaar wissen', tags: ['systeem'], template: true, danger: true,
    note: 'Overschrijft alle vrije ruimte zodat verwijderde bestanden niet terug te halen zijn. Duurt lang en is zwaar voor een SSD.' },
  { cmd: 'winget list', label: 'Geïnstalleerde programma\'s', tags: ['systeem'],
    note: 'winget install <naam> installeert er een, winget upgrade --all werkt alles bij. Zit standaard in Windows 11 en recente Windows 10.' },
  { cmd: 'powercfg /energy', label: 'Energierapport maken', tags: ['systeem'],
    note: 'Draait een minuut en schrijft een rapport met instellingen die stroom kosten.' },
  { cmd: 'color 0a', label: 'Kleuren van het venster', tags: ['prompt'], template: true,
    note: 'Eerste cijfer is de achtergrond, tweede de tekst. 0a is zwart met groen; color zonder cijfers zet het terug.' },
  { cmd: 'chcp 65001', label: 'Tekenset op UTF-8 zetten', tags: ['prompt'], template: true,
    note: 'Nodig als accenten of emoji als rare tekens verschijnen.' },
  { cmd: 'doskey /history', label: 'Commando\'s van deze sessie', tags: ['prompt'], template: true,
    note: 'Geldt alleen voor het venster waarin je werkt; F7 toont dezelfde lijst als menu.' },

  // ── Nog meer bat-bouwstenen ───────────────────────────────────────────────
  { cmd: 'choice /c jn /m "Doorgaan"', label: 'Ja/nee vragen', tags: ['bat'], snippet: true,
    note: 'De keuze komt in %errorlevel%: 1 voor de eerste letter, 2 voor de tweede. Controleer van hoog naar laag.' },
  { cmd: 'if "%~1"=="" (\r\n  echo Geef een bestandsnaam mee.\r\n  exit /b 1\r\n)', label: 'Controleren of er een argument is', tags: ['bat'], snippet: true,
    note: 'De tilde haalt eventuele aanhalingstekens weg, zodat de vergelijking ook klopt bij een pad met spaties.' },
  { cmd: 'echo Bestand: %~n1  Extensie: %~x1  Map: %~dp1', label: 'Onderdelen van een pad', tags: ['bat'], snippet: true,
    note: '~n is de naam, ~x de extensie, ~dp de schijf en map, ~f het volledige pad. Werkt op %1 tot %9 en op lusvariabelen.' },
  { cmd: 'pushd "C:\\ergens"\r\nrem werk hier\r\npopd', label: 'Tijdelijk naar een andere map', tags: ['bat'], snippet: true,
    note: 'popd brengt je terug waar je vandaan kwam. pushd kan ook naar netwerkpaden, die krijgen dan een tijdelijke schijfletter.' },
  { cmd: 'shift', label: 'Argumenten opschuiven', tags: ['bat'], snippet: true,
    note: 'Na shift wordt %2 het nieuwe %1. Zo loop je door een onbekend aantal argumenten.' },
  { cmd: 'echo %random%', label: 'Willekeurig getal', tags: ['bat'], snippet: true,
    note: 'Een getal tussen 0 en 32767. Voor een bereik: set /a getal=%random% %% 100' },
  { cmd: 'set /a som=3+4', label: 'Rekenen', tags: ['bat'], snippet: true,
    note: 'Alleen hele getallen. Het procentteken voor de rest bij deling schrijf je in een bat-bestand dubbel: %%' },
  { cmd: 'endlocal', label: 'Variabelen weer loslaten', tags: ['bat'], snippet: true,
    note: 'Hoort bij setlocal. Alles wat je ertussen zet, verdwijnt daarna weer — zo laat je geen rommel achter.' },
  { cmd: 'commando 2>nul', label: 'Alleen foutmeldingen wegslikken', tags: ['bat'], snippet: true,
    note: 'De gewone uitvoer blijft zichtbaar; alleen wat naar de foutuitvoer gaat verdwijnt.' },
  { cmd: 'for /l %%i in (1,1,10) do echo %%i', label: 'Tellen van 1 tot 10', tags: ['bat'], snippet: true,
    note: 'De drie getallen zijn begin, stap en eind.' },
  { cmd: 'if not exist "map" mkdir "map"', label: 'Map maken als hij nog niet bestaat', tags: ['bat'], snippet: true },
  { cmd: 'start "" /wait "programma.exe"', label: 'Wachten tot een programma klaar is', tags: ['bat'], snippet: true,
    note: 'Zonder /wait gaat je script meteen verder terwijl het programma nog draait.' },
  // ── Kant-en-klare bat-recepten ────────────────────────────────────────────
  // Complete stukjes die je zo in een script kunt plakken.
  { tags: ['bat', 'recept'], snippet: true, label: 'Reservekopie in een map met de datum van vandaag',
    note: 'De datum via PowerShell ophalen is betrouwbaarder dan %date% uitknippen: dat laatste ziet er per taalinstelling anders uit.',
    cmd: 'for /f %%i in (\'powershell -NoProfile -Command "Get-Date -Format yyyy-MM-dd"\') do set "STAMP=%%i"\r\nrobocopy "C:\\bron" "D:\\backup\\%STAMP%" /e' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Logbestanden ouder dan 30 dagen opruimen',
    note: 'forfiles rekent in dagen: -30 betekent ouder dan dertig dagen. Vervang del door echo om eerst te zien wat er weg zou gaan.',
    cmd: 'forfiles /p "C:\\logs" /s /m *.log /d -30 /c "cmd /c del @path"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Programma starten als het nog niet draait',
    note: 'find geeft errorlevel 1 als er niets gevonden is; dan draait het dus nog niet.',
    cmd: 'tasklist /fi "imagename eq programma.exe" | find /i "programma.exe" >nul\r\nif errorlevel 1 start "" "C:\\pad\\programma.exe"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Wachten tot een programma is afgesloten',
    note: 'Handig voordat je bestanden vervangt die dat programma nog vasthoudt.',
    cmd: ':wacht\r\ntasklist /fi "imagename eq programma.exe" | find /i "programma.exe" >nul\r\nif not errorlevel 1 (\r\n  timeout /t 2 /nobreak >nul\r\n  goto wacht\r\n)' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Wachten tot een bestand verschijnt',
    note: 'Bijvoorbeeld om te wachten tot een ander proces klaar is en een seinbestand neerzet.',
    cmd: ':wacht\r\nif not exist "klaar.txt" (\r\n  timeout /t 5 /nobreak >nul\r\n  goto wacht\r\n)\r\necho Het bestand is er.' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Uitvoer van een commando in een variabele zetten',
    note: 'delims= zorgt dat de hele regel meekomt, ook met spaties erin.',
    cmd: 'for /f "delims=" %%i in (\'hostname\') do set "NAAM=%%i"\r\necho Deze computer heet %NAAM%' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Een tekstbestand regel voor regel doorlopen',
    note: 'usebackq is nodig omdat het pad tussen aanhalingstekens staat; zonder dat leest for de naam als tekst in plaats van als bestand.',
    cmd: 'for /f "usebackq delims=" %%r in ("lijst.txt") do (\r\n  echo Regel: %%r\r\n)' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Tellen terwijl je door bestanden loopt',
    note: 'Binnen een blok moet je !AANTAL! gebruiken in plaats van %AANTAL%, anders staat er steeds dezelfde beginwaarde.',
    cmd: 'setlocal enabledelayedexpansion\r\nset /a AANTAL=0\r\nfor %%f in (*.txt) do (\r\n  set /a AANTAL+=1\r\n  echo !AANTAL!: %%f\r\n)\r\necho Totaal: !AANTAL!' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Controleren of er internet is',
    note: '-w 2000 wacht maximaal twee seconden, zodat je script niet blijft hangen als er niets reageert.',
    cmd: 'ping -n 1 -w 2000 8.8.8.8 >nul\r\nif errorlevel 1 (\r\n  echo Geen verbinding.\r\n  exit /b 1\r\n)\r\necho Verbinding in orde.' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Fout wegschrijven naar een logbestand',
    note: 'Zet dit achter elke stap die mis kan gaan, dan weet je achteraf waar het strandde.',
    cmd: 'jouw-commando\r\nif errorlevel 1 (\r\n  echo [%date% %time%] MISLUKT: jouw-commando >> "fouten.log"\r\n  exit /b 1\r\n)' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Bestanden hernoemen met een voorvoegsel',
    note: 'Test eerst met echo in plaats van ren om te zien wat er zou gebeuren.',
    cmd: 'for %%f in (*.jpg) do ren "%%f" "vakantie_%%f"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Alle submappen doorlopen',
    note: '/d beperkt het tot mappen, /r duikt de hele boom in.',
    cmd: 'for /d /r %%m in (*) do echo Map: %%m' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Zip maken zonder extra programma',
    note: 'tar zit sinds Windows 10 in Windows; -a kiest de compressie op basis van de extensie.',
    cmd: 'tar -a -c -f "backup.zip" "map-om-in-te-pakken"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Een dienst herstarten',
    note: 'De dubbele & voert het starten alleen uit als het stoppen gelukt is. Vereist beheerdersrechten.',
    cmd: 'net stop "Naam van dienst" && net start "Naam van dienst"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Meerdere programma\'s achter elkaar starten',
    note: 'Zonder /wait gaan ze tegelijk open; met /wait wacht je script tot het vorige klaar is.',
    cmd: 'start "" "C:\\pad\\eerste.exe"\r\nstart "" "C:\\pad\\tweede.exe"' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Vragen om bevestiging voordat je doorgaat',
    note: 'De keuze komt in errorlevel: 1 is de eerste letter (j), 2 de tweede (n). Controleer altijd van hoog naar laag.',
    cmd: 'choice /c jn /m "Weet je het zeker"\r\nif errorlevel 2 (\r\n  echo Afgebroken.\r\n  exit /b 0\r\n)\r\necho Doorgaan maar.' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Netwerkschijf koppelen als hij er nog niet is',
    note: '/persistent:no zorgt dat de koppeling na een herstart weer weg is.',
    cmd: 'if not exist Z:\\ net use Z: \\\\server\\map /persistent:no' },

  { tags: ['bat', 'recept'], snippet: true, label: 'Alleen doorgaan met beheerdersrechten',
    note: 'Zonder deze controle mislukken beheerderscommando\'s halverwege, vaak zonder duidelijke melding.',
    cmd: 'net session >nul 2>&1\r\nif errorlevel 1 (\r\n  echo Start dit bestand met rechtermuisknop, "Als administrator uitvoeren".\r\n  pause\r\n  exit /b 1\r\n)' },

  // ── Flutter ───────────────────────────────────────────────────────────────
  { cmd: 'flutter doctor', label: 'Flutter-installatie controleren', tags: ['flutter'],
    note: 'Eerste check bij problemen. Toont wat er nog ontbreekt (Android SDK, Visual Studio, enz.).' },
  { cmd: 'flutter doctor -v', label: 'Uitgebreide Flutter-diagnose', tags: ['flutter'],
    note: 'Zelfde als flutter doctor, maar met alle paden en versies erbij — handig om te delen bij hulpvragen.' },
  { cmd: 'flutter --version', label: 'Flutter-versie', tags: ['flutter'] },
  { cmd: 'flutter channel', label: 'Welk Flutter-kanaal?', tags: ['flutter'],
    note: 'stable is standaard. Overstappen: flutter channel stable (of beta / master).' },
  { cmd: 'flutter channel stable', label: 'Overschakelen naar stable', tags: ['flutter'] },
  { cmd: 'flutter upgrade', label: 'Flutter bijwerken', tags: ['flutter'],
    note: 'Haalt de nieuwste versie van je huidige kanaal op. Duurt even en vraagt soms om bevestiging.' },
  { cmd: 'flutter downgrade', label: 'Flutter één versie terugzetten', tags: ['flutter'], template: true,
    note: 'Handig als een upgrade iets breekt. Je kunt ook een versie opgeven: flutter downgrade 3.22.0' },
  { cmd: 'flutter config --list', label: 'Flutter-configuratie tonen', tags: ['flutter'] },
  { cmd: 'flutter create mijn_app', label: 'Nieuw Flutter-project', tags: ['flutter'], template: true,
    note: 'Vervang mijn_app door de projectnaam (kleine letters, underscores). Voeg --org com.bedrijf toe voor de package-naam.' },
  { cmd: 'flutter create --platforms=android,ios,web,windows .', label: 'Platformen toevoegen aan bestaand project', tags: ['flutter'],
    note: 'Draai dit in de projectmap. Handig als je bijvoorbeeld later Windows of web wilt bijzetten.' },

  // ── Flutter: apparaten en draaien ─────────────────────────────────────────
  { cmd: 'flutter devices', label: 'Beschikbare apparaten', tags: ['flutter'],
    note: 'Toont emulators, aangesloten telefoons en desktop/web-targets.' },
  { cmd: 'flutter emulators', label: 'Beschikbare emulators', tags: ['flutter'] },
  { cmd: 'flutter emulators --launch Pixel_6', label: 'Emulator starten', tags: ['flutter'], template: true,
    note: 'De naam komt uit flutter emulators. Start eerst de emulator, daarna flutter run.' },
  { cmd: 'flutter run', label: 'App starten (debug)', tags: ['flutter'],
    note: 'Kiest automatisch een apparaat. Tijdens het draaien: r = hot reload, R = hot restart, q = stoppen.' },
  { cmd: 'flutter run -d chrome', label: 'App starten in Chrome', tags: ['flutter', 'web'] },
  { cmd: 'flutter run -d windows', label: 'App starten op Windows', tags: ['flutter', 'windows'] },
  { cmd: 'flutter run -d mobile', label: 'App starten op Android', tags: ['flutter', 'android'],
    note: 'Gebruikt de categorie "mobile" (zoals flutter devices die toont), niet "android" — dat is geen geldige device-selector.' },
  { cmd: 'flutter run --release', label: 'App starten in release-modus', tags: ['flutter'],
    note: 'Geen hot reload, wel veel sneller — dichter bij wat de gebruiker krijgt.' },
  { cmd: 'flutter run --profile', label: 'App starten in profile-modus', tags: ['flutter'],
    note: 'Voor performance-metingen in DevTools: wel geoptimaliseerd, maar met profiling aan.' },
  { cmd: 'flutter run --flavor productie', label: 'App starten met een flavor', tags: ['flutter'], template: true,
    note: 'Alleen als je project flavors heeft ingesteld (Android productFlavors / iOS schemes).' },
  { cmd: 'flutter attach', label: 'Koppelen aan draaiende app', tags: ['flutter'], template: true,
    note: 'Voor een app die al draait (bijv. vanuit Android Studio). Opent hot reload vanuit deze terminal.' },
  { cmd: 'flutter install', label: 'Release-build op apparaat zetten', tags: ['flutter'],
    note: 'Installeert de laatst gebouwde app. Bouw eerst met flutter build apk of appbundle.' },

  // ── Flutter: packages ─────────────────────────────────────────────────────
  { cmd: 'flutter pub get', label: 'Packages ophalen', tags: ['flutter', 'pub'],
    note: 'Na het klonen van een project of na wijzigingen in pubspec.yaml.' },
  { cmd: 'flutter pub upgrade', label: 'Packages bijwerken binnen begrensingen', tags: ['flutter', 'pub'],
    note: 'Blijft binnen de versies in pubspec.yaml. Voor major updates: flutter pub upgrade --major-versions' },
  { cmd: 'flutter pub upgrade --major-versions', label: 'Packages ook naar major-versies', tags: ['flutter', 'pub'],
    note: 'Past pubspec.yaml aan. Controleer daarna of alles nog compileert.' },
  { cmd: 'flutter pub outdated', label: 'Welke packages zijn verouderd?', tags: ['flutter', 'pub'] },
  { cmd: 'flutter pub add provider', label: 'Package toevoegen', tags: ['flutter', 'pub'], template: true,
    note: 'Vervang provider door de packagenaam van pub.dev. Schrijft meteen in pubspec.yaml.' },
  { cmd: 'flutter pub add --dev build_runner', label: 'Dev-package toevoegen', tags: ['flutter', 'pub'], template: true,
    note: 'Voor tools die alleen bij ontwikkelen nodig zijn (tests, codegeneratie).' },
  { cmd: 'flutter pub remove provider', label: 'Package verwijderen', tags: ['flutter', 'pub'], template: true },
  { cmd: 'flutter pub cache repair', label: 'Pub-cache repareren', tags: ['flutter', 'pub'],
    note: 'Laatste redmiddel bij rare download- of hashfouten.' },
  { cmd: 'flutter pub publish --dry-run', label: 'Package publiceren (droog)', tags: ['flutter', 'pub'],
    note: 'Controleert of je package klaar is voor pub.dev, zonder echt te publiceren.' },

  // ── Flutter: schonen, analyseren, testen ──────────────────────────────────
  { cmd: 'flutter clean', label: 'Build-cache legen', tags: ['flutter'],
    note: 'Verwijdert build/ en .dart_tool/. Daarna opnieuw flutter pub get. Helpt bij rare buildfouten.' },
  { cmd: 'flutter analyze', label: 'Code analyseren', tags: ['flutter'],
    note: 'Statische analyse: ongebruikte imports, typefouten, lintregels.' },
  { cmd: 'flutter test', label: 'Tests draaien', tags: ['flutter', 'test'] },
  { cmd: 'flutter test --coverage', label: 'Tests met dekking', tags: ['flutter', 'test'],
    note: 'Schrijft coverage/lcov.info. Open die daarna met een coverage-viewer.' },
  { cmd: 'flutter test test/pad/naar_test.dart', label: 'Één testbestand draaien', tags: ['flutter', 'test'], template: true },
  { cmd: 'dart format .', label: 'Alle Dart-bestanden formatteren', tags: ['flutter', 'dart'] },
  { cmd: 'dart format lib test', label: 'lib en test formatteren', tags: ['flutter', 'dart'] },
  { cmd: 'dart fix --dry-run', label: 'Automatische fixes tonen', tags: ['flutter', 'dart'],
    note: 'Laat zien wat dart fix zou aanpassen, zonder te schrijven.' },
  { cmd: 'dart fix --apply', label: 'Automatische fixes toepassen', tags: ['flutter', 'dart'] },
  { cmd: 'flutter gen-l10n', label: 'Vertalingen genereren', tags: ['flutter'],
    note: 'Voor projecten met flutter: generate: true / l10n.yaml. Maakt de AppLocalizations-klassen.' },

  // ── Flutter: bouwen ───────────────────────────────────────────────────────
  { cmd: 'flutter build apk', label: 'APK bouwen (debug-achtig default)', tags: ['flutter', 'android', 'build'],
    note: 'Voor een winkel-release meestal: flutter build apk --release of beter: appbundle.' },
  { cmd: 'flutter build apk --release', label: 'Release-APK bouwen', tags: ['flutter', 'android', 'build'],
    note: 'Eén APK voor alle ABI\'s. Voor kleinere downloads: --split-per-abi.' },
  { cmd: 'flutter build apk --release --split-per-abi', label: 'Release-APK per processorarchitectuur', tags: ['flutter', 'android', 'build'],
    note: 'Maakt aparte APK\'s (arm64-v8a, armeabi-v7a, x86_64) — kleiner om te delen of sideloaden.' },
  { cmd: 'flutter build appbundle', label: 'Android App Bundle bouwen', tags: ['flutter', 'android', 'build'],
    note: 'Dit is wat je naar de Play Store uploadt.' },
  { cmd: 'flutter build appbundle --release', label: 'Release App Bundle', tags: ['flutter', 'android', 'build'] },
  { cmd: 'flutter build web', label: 'Web-build maken', tags: ['flutter', 'web', 'build'],
    note: 'Output in build/web/. Host die map op een webserver of Firebase Hosting.' },
  { cmd: 'flutter build web --release --web-renderer canvaskit', label: 'Web-build met CanvasKit', tags: ['flutter', 'web', 'build'],
    note: 'Betere weergave, grotere download. Alternatief: --web-renderer html.' },
  { cmd: 'flutter build windows', label: 'Windows-build maken', tags: ['flutter', 'windows', 'build'],
    note: 'Vereist Visual Studio met de "Desktop development with C++"-workload.' },
  { cmd: 'flutter build windows --release', label: 'Windows release-build', tags: ['flutter', 'windows', 'build'] },
  { cmd: 'flutter build ios --release', label: 'iOS-build (alleen op macOS)', tags: ['flutter', 'ios', 'build'], template: true,
    note: 'Werkt alleen op een Mac met Xcode. Op Windows kun je dit overslaan.' },
  { cmd: 'flutter build ipa', label: 'IPA voor App Store / TestFlight', tags: ['flutter', 'ios', 'build'], template: true,
    note: 'Alleen op macOS. Maakt een archief dat je in Xcode of Transporter kunt indienen.' },

  // ── Flutter: overig ───────────────────────────────────────────────────────
  { cmd: 'flutter screenshot', label: 'Screenshot van draaiende app', tags: ['flutter'],
    note: 'Slaat een PNG op terwijl flutter run actief is.' },
  { cmd: 'flutter logs', label: 'Logcat/logs van het apparaat', tags: ['flutter'],
    note: 'Toont de logs van de Flutter-app op het aangesloten apparaat.' },
  { cmd: 'flutter symbolize -i stack.txt -d app.android-arm64.symbols', label: 'Crashstack ontcijferen', tags: ['flutter'], template: true,
    note: 'Voor release-crashes: combineer de stacktrace met het symbols-bestand uit de build.' },
  { cmd: 'flutter precache', label: 'Flutter-artifacts vooraf ophalen', tags: ['flutter'],
    note: 'Handig offline of om de eerste build sneller te maken.' },
  { cmd: 'flutter config --enable-web', label: 'Web-ondersteuning aanzetten', tags: ['flutter', 'web'] },
  { cmd: 'flutter config --enable-windows-desktop', label: 'Windows-desktop aanzetten', tags: ['flutter', 'windows'] },
  { cmd: 'flutter pub run build_runner build --delete-conflicting-outputs', label: 'Codegeneratie (build_runner)', tags: ['flutter', 'dart'],
    note: 'Voor json_serializable, freezed, injectable, enz. Het --delete-conflicting-outputs voorkomt conflicten.' },
  { cmd: 'flutter pub run build_runner watch --delete-conflicting-outputs', label: 'Codegeneratie live bijhouden', tags: ['flutter', 'dart'],
    note: 'Blijft draaien en regenereert bij elke wijziging. Stoppen met Ctrl+C.' },
  { cmd: 'dart run build_runner build --delete-conflicting-outputs', label: 'build_runner via dart run', tags: ['flutter', 'dart'],
    note: 'Nieuwere variant van flutter pub run build_runner …' },

  // ── Dart ──────────────────────────────────────────────────────────────────
  { cmd: 'dart --version', label: 'Dart-versie', tags: ['dart'] },
  { cmd: 'dart pub get', label: 'Packages ophalen (Dart)', tags: ['dart', 'pub'] },
  { cmd: 'dart analyze', label: 'Dart-analyse', tags: ['dart'] },
  { cmd: 'dart test', label: 'Dart-tests draaien', tags: ['dart', 'test'] },
  { cmd: 'dart create mijn_cli', label: 'Nieuw Dart-project', tags: ['dart'], template: true },
  { cmd: 'dart compile exe bin/main.dart -o app.exe', label: 'Dart naar exe compileren', tags: ['dart'], template: true,
    note: 'Maakt een losstaand Windows-programma van je Dart-code.' },

  // ── Android / adb (vaak naast Flutter) ────────────────────────────────────
  { cmd: 'adb devices', label: 'Aangesloten Android-apparaten', tags: ['android', 'adb'],
    note: 'Staat er "unauthorized"? Kijk op de telefoon en accepteer USB-debugging.' },
  { cmd: 'adb kill-server && adb start-server', label: 'ADB-server herstarten', tags: ['android', 'adb'],
    note: 'Eerste ding om te proberen als apparaten niet meer verschijnen.' },
  { cmd: 'adb logcat', label: 'Android-logboek live', tags: ['android', 'adb'], template: true,
    note: 'Veel ruis. Filteren: adb logcat | findstr flutter' },
  { cmd: 'adb logcat | findstr /i flutter', label: 'Alleen Flutter-regels uit logcat', tags: ['android', 'adb', 'flutter'] },
  { cmd: 'adb install -r "build\\app\\outputs\\flutter-apk\\app-release.apk"', label: 'APK installeren / vervangen', tags: ['android', 'adb'], template: true,
    note: '-r vervangt een bestaande installatie. Pas het pad aan als je --split-per-abi gebruikte.' },
  { cmd: 'adb uninstall com.voorbeeld.app', label: 'App van apparaat verwijderen', tags: ['android', 'adb'], template: true },
  { cmd: 'adb reverse tcp:8080 tcp:8080', label: 'Poort doorzetten naar de PC', tags: ['android', 'adb'], template: true,
    note: 'Handig zodat de telefoon localhost:8080 op je PC kan bereiken (API, Chrome DevTools, enz.).' },
  { cmd: 'adb shell pm list packages | findstr jouwapp', label: 'Package-naam opzoeken', tags: ['android', 'adb'], template: true },
  { cmd: 'adb reboot', label: 'Telefoon/emulator herstarten', tags: ['android', 'adb'] },
  { cmd: 'sdkmanager --list', label: 'Geïnstalleerde Android SDK-onderdelen', tags: ['android'], template: true,
    note: 'Vereist dat sdkmanager in je PATH staat (Android SDK cmdline-tools).' },

  // ── Git (dagelijks bij Flutter-projecten) ─────────────────────────────────
  { cmd: 'git status', label: 'Status van de repository', tags: ['git'] },
  { cmd: 'git status -sb', label: 'Korte git-status', tags: ['git'] },
  { cmd: 'git diff', label: 'Lokale wijzigingen tonen', tags: ['git'] },
  { cmd: 'git diff --staged', label: 'Gestagede wijzigingen tonen', tags: ['git'] },
  { cmd: 'git log --oneline -20', label: 'Laatste 20 commits', tags: ['git'] },
  { cmd: 'git log --oneline --graph --all -30', label: 'Commit-geschiedenis als grafiek', tags: ['git'] },
  { cmd: 'git add .', label: 'Alle wijzigingen stagen', tags: ['git'],
    note: 'Voegt nieuwe en gewijzigde bestanden toe. Kijk daarna met git status of je niets te veel meeneemt.' },
  { cmd: 'git add -p', label: 'Interactief stagen', tags: ['git'], template: true,
    note: 'Kiest per stukje wat er in de commit komt. Handig om rommel buiten de commit te houden.' },
  { cmd: 'git commit -m "bericht"', label: 'Commit maken', tags: ['git'], template: true },
  { cmd: 'git commit --amend --no-edit', label: 'Laatste commit aanvullen', tags: ['git'],
    note: 'Alleen als je die commit nog niet gepusht hebt (of force-push bewust wilt).' },
  { cmd: 'git pull', label: 'Remote ophalen en mergen', tags: ['git'] },
  { cmd: 'git pull --rebase', label: 'Remote ophalen met rebase', tags: ['git'],
    note: 'Houdt de geschiedenis linearer. Bij conflicten: oplossen, git add, git rebase --continue.' },
  { cmd: 'git push', label: 'Commits naar remote sturen', tags: ['git'] },
  { cmd: 'git push -u origin HEAD', label: 'Nieuwe branch pushen en koppelen', tags: ['git'],
    note: 'Eerste push van een lokale branch: zet de upstream in één keer goed.' },
  { cmd: 'git fetch --all --prune', label: 'Remotes bijwerken', tags: ['git'],
    note: '--prune ruimt verwijderde remote-branches lokaal op.' },
  { cmd: 'git checkout -b feature/naam', label: 'Nieuwe branch maken', tags: ['git'], template: true },
  { cmd: 'git switch main', label: 'Naar branch wisselen', tags: ['git'], template: true },
  { cmd: 'git branch -a', label: 'Alle branches tonen', tags: ['git'] },
  { cmd: 'git stash -u', label: 'Wijzigingen tijdelijk wegzetten', tags: ['git'],
    note: '-u neemt ook untracked bestanden mee.' },
  { cmd: 'git stash pop', label: 'Gestashte wijzigingen terugzetten', tags: ['git'] },
  { cmd: 'git stash list', label: 'Stash-lijst', tags: ['git'] },
  { cmd: 'git remote -v', label: 'Remotes tonen', tags: ['git'] },
  { cmd: 'git clone https://github.com/org/repo.git', label: 'Repository klonen', tags: ['git'], template: true },
  { cmd: 'git restore bestand.dart', label: 'Bestand terugzetten naar laatste commit', tags: ['git'], template: true,
    note: 'Gooit lokale wijzigingen in dat bestand weg. Voor gestagede: git restore --staged bestand.dart' },
  { cmd: 'git revert HEAD --no-edit', label: 'Laatste commit terugdraaien met nieuwe commit', tags: ['git'],
    note: 'Veiliger dan reset op een gedeelde branch: maakt een tegengestelde commit.' },
  { cmd: 'git reset --soft HEAD~1', label: 'Laatste commit ongedaan (wijzigingen behouden)', tags: ['git'], danger: true,
    note: 'Haalt de commit weg maar laat de wijzigingen gestaged staan. Niet gebruiken op commits die al gepusht zijn, tenzij je weet wat je doet.' },
  { cmd: 'git clean -fd', label: 'Untracked bestanden en mappen wissen', tags: ['git'], danger: true,
    note: 'Onherroepelijk. Test eerst met git clean -fdn (dry-run).' },

  // ── Node / tooling die je naast Flutter tegenkomt ─────────────────────────
  { cmd: 'npm install', label: 'npm-packages installeren', tags: ['node'],
    note: 'Soms heeft een Flutter-repo een tooling-map (CI-scripts, web-helpers) met package.json.' },
  { cmd: 'npm run build', label: 'npm build-script', tags: ['node'], template: true },
  { cmd: 'npx --yes', label: 'Eenmalig npm-pakket draaien', tags: ['node'], template: true,
    note: 'Voorbeeld: npx --yes create-something. De --yes slaat de bevestiging over.' },
  { cmd: 'firebase login', label: 'Aanmelden bij Firebase CLI', tags: ['firebase'], template: true },
  { cmd: 'firebase projects:list', label: 'Firebase-projecten tonen', tags: ['firebase'] },
  { cmd: 'flutterfire configure', label: 'FlutterFire voor dit project instellen', tags: ['firebase', 'flutter'], template: true,
    note: 'Genereert firebase_options.dart. Vereist firebase-tools en de FlutterFire CLI.' },
  { cmd: 'firebase deploy --only hosting', label: 'Firebase Hosting deployen', tags: ['firebase', 'web'], template: true,
    note: 'Vaak na flutter build web. Controleer firebase.json op de public-map (meestal build/web).' },

  // ── AI in het uitvoervenster ──────────────────────────────────────────────
  // Deze gaan nooit naar de shell: alles met een / ervoor handelt de app zelf
  // af. Welke diensten er zijn staat in ai-providers.js.
  { cmd: '/diensten', label: 'Welke AI-diensten staan klaar', tags: ['ai'],
    note: 'Toont per dienst of er een sleutel is en waar die vandaan komt, en welke je zonder betaalgegevens kunt proberen.' },
  { cmd: '/use claude', label: 'In gesprek met Claude', tags: ['ai'],
    note: 'Nog een keer dezelfde dienst kiezen zet je terug in de shell. Dat kan ook met /shell.' },
  { cmd: '/use gemini', label: 'In gesprek met Gemini', tags: ['ai'],
    note: 'Gratis sleutel op aistudio.google.com/apikey.' },
  { cmd: '/use ollama', label: 'In gesprek met een model op je eigen pc', tags: ['ai'],
    note: 'Via Ollama. Geen sleutel, geen internet, geen rekening. Kiest zelf het eerste model dat je hebt gedownload.' },
  { cmd: '/use openrouter', label: 'In gesprek via OpenRouter', tags: ['ai'],
    note: 'Eén sleutel voor honderden modellen. Alles met :free achteraan kost niets.' },
  { cmd: '/ai leg deze fout uit', label: 'Eén vraag stellen zonder van modus te wisselen', tags: ['ai'], template: true },
  { cmd: '/sleutel plak-hier-je-sleutel', label: 'API-sleutel opslaan', tags: ['ai'], template: true,
    note: 'Geldt voor de dienst die op dat moment actief is, dus eerst /use. De sleutel komt versleuteld in ai-keys.json en verschijnt niet in beeld.' },
  { cmd: '/modellen live', label: 'Modellen ophalen bij de dienst zelf', tags: ['ai'],
    note: 'De lijst in de code veroudert; deze niet. Bij een lokale server is dit de enige manier om te zien wat je hebt gedownload.' },
  { cmd: '/model opus', label: 'Ander model kiezen', tags: ['ai'], template: true,
    note: 'Een deel van de naam is genoeg: opus vindt claude-opus-5.' },
  { cmd: '/systeem antwoord kort en in het Nederlands', label: 'Systeemprompt instellen', tags: ['ai'], template: true,
    note: 'Geldt voor alle diensten. Leeg laten wist hem.' },
  { cmd: '/nieuw', label: 'Gesprek wissen en opnieuw beginnen', tags: ['ai'],
    note: 'Wist wat de AI zich herinnert. Alleen het scherm leegmaken doe je met clear; dat laat het gesprek staan.' },
  { cmd: '/stop', label: 'Lopend antwoord afbreken', tags: ['ai'] },
  { cmd: '/shell', label: 'Gespreksmodus uit, terug naar de shell', tags: ['ai'],
    note: 'Kan ook door gewoon exit te typen tijdens een gesprek. Buiten een gesprek sluit exit CommandDeck zelf.' },
  { cmd: '/knoppen uit', label: 'Knoppenrij per AI-dienst verbergen', tags: ['ai'],
    note: '/knoppen aan zet hem weer terug. De rij staat bij een project en in de cmd-sectie.' },
  { cmd: '/knoppen aan', label: 'Knoppenrij per AI-dienst tonen', tags: ['ai'] },
  { cmd: '/hulp', label: 'Alle AI-commando\'s op een rij', tags: ['ai'] },

  // Losse AI-programma's. Die praten niet via CommandDeck maar draaien zelf in
  // een echte terminal in het uitvoervenster, zoals Claude Code dat al deed.
  { cmd: 'claude', label: 'Claude Code starten', tags: ['ai'],
    note: 'Draait in een echte terminal in het uitvoervenster. Sluiten met exit.' },
  { cmd: 'codex', label: 'Codex CLI starten (ChatGPT)', tags: ['ai'],
    note: 'Zit in elk ChatGPT-abonnement, ook het gratis. Eerste keer opent een browser om in te loggen. Installeren: npm install -g @openai/codex' },
  { cmd: 'gemini', label: 'Gemini CLI starten', tags: ['ai'],
    note: 'Inloggen met je Google-account. Installeren: npm install -g @google/gemini-cli' },
  { cmd: 'ollama run qwen2.5-coder:7b', label: 'Lokaal model in een chat', tags: ['ai'], template: true,
    note: 'Draait op je eigen pc, zonder internet. Eerst ophalen met ollama pull.' },

  // ── Het woordenboek zelf ──────────────────────────────────────────────────
  { cmd: 'theme', label: 'Welke thema\'s zijn er', tags: ['woordenboek'],
    note: 'Werkt in de cmd-sectie en bij een project. Een thema is het label waarop je in het woordenboek filtert.' },
  { cmd: 'theme deploy', label: 'Eigen thema aanmaken', tags: ['woordenboek'], template: true,
    note: 'Bestaat het thema al, dan zie je wat erin zit.' },
  { cmd: 'theme deploy npm run build', label: 'Commando aan een thema toevoegen', tags: ['woordenboek'], template: true,
    note: 'Zet het commando meteen in het woordenboek onder dat thema. Zo bouw je vanuit de commandobalk je eigen categorie op.' },
  { cmd: 'theme wis deploy', label: 'Eigen thema weghalen', tags: ['woordenboek'], template: true,
    note: 'De labels op de commando\'s zelf blijven staan.' },
]

const { PS_COMMANDS } = require('./ps-library')

module.exports = { BUILTIN_COMMANDS: BUILTIN_COMMANDS.concat(PS_COMMANDS) }
