// PowerShell-startvoorraad voor het commando-woordenboek.
//
// Zelfde vorm als cmd-library.js, extra veld `shell: 'powershell'` zodat
// uitvoeren vanuit het woordenboek naar de powershell-sectie gaat en niet
// naar cmd.exe. Elke regel heeft ook het label `powershell`, zodat je er
// in het woordenboek op kunt filteren.
//
// Gericht op Windows PowerShell 5.1 (powershell.exe), niet alleen pwsh.

function ps(row) {
  return {
    shell: 'powershell',
    ...row,
    tags: ['powershell', ...(row.tags || []).filter(t => t !== 'powershell')],
  }
}

const PS_COMMANDS = [
  // ── Bestanden ─────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-ChildItem', label: 'Bestanden in deze map', tags: ['bestanden'],
    note: 'De powershell-variant van dir. Voeg -Force toe voor verborgen items, -Recurse voor submappen.' }),
  ps({ cmd: 'Get-ChildItem -Force', label: 'Ook verborgen bestanden tonen', tags: ['bestanden'] }),
  ps({ cmd: 'Get-ChildItem -Recurse -File', label: 'Alle bestanden onder deze map', tags: ['bestanden'],
    note: 'Alleen bestanden, geen mappen. Beperk met -Filter *.log of pipe naar Where-Object.' }),
  ps({ cmd: 'Get-ChildItem -Recurse -File | Select-Object FullName, Length, LastWriteTime',
    label: 'Bestanden met grootte en datum', tags: ['bestanden'] }),
  ps({ cmd: 'Get-Item .', label: 'Gegevens van deze map', tags: ['bestanden'] }),
  ps({ cmd: 'Get-Content bestand.txt', label: 'Inhoud van een bestand tonen', tags: ['bestanden'], template: true,
    note: 'Voeg -Tail 40 toe voor alleen de laatste regels, -Wait om mee te lezen terwijl erbij geschreven wordt.' }),
  ps({ cmd: 'Get-Content bestand.txt -Tail 50', label: 'Laatste regels van een bestand', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Set-Content -Path bestand.txt -Value \'tekst\'', label: 'Bestand overschrijven', tags: ['bestanden'], template: true,
    note: 'Maakt het bestand aan als het nog niet bestaat. Add-Content plakt eronder vast.' }),
  ps({ cmd: 'Add-Content -Path log.txt -Value (Get-Date)', label: 'Regel aan een bestand toevoegen', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Copy-Item bron.txt doel.txt', label: 'Bestand of map kopiëren', tags: ['bestanden'], template: true,
    note: 'Voor een map: Copy-Item bron doel -Recurse.' }),
  ps({ cmd: 'Move-Item oud.txt nieuw.txt', label: 'Verplaatsen of hernoemen', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Rename-Item oud.txt nieuw.txt', label: 'Hernoemen', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Remove-Item bestand.txt', label: 'Bestand verwijderen', tags: ['bestanden'], template: true,
    note: 'Gaat niet naar de prullenbak. Voor een map met inhoud: Remove-Item map -Recurse -Force.' }),
  ps({ cmd: 'Remove-Item "map" -Recurse -Force', label: 'Map met inhoud verwijderen', tags: ['bestanden'], template: true, danger: true,
    note: 'Onherroepelijk — geen prullenbak, geen extra vraag vanuit powershell zelf.' }),
  ps({ cmd: 'New-Item -ItemType Directory -Name "nieuwe map"', label: 'Map aanmaken', tags: ['bestanden'], template: true }),
  ps({ cmd: 'New-Item -ItemType File -Name "nieuw.txt"', label: 'Leeg bestand maken', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Test-Path "C:\\pad"', label: 'Bestaat dit pad?', tags: ['bestanden'], template: true,
    note: 'Geeft True of False. In een script: if (Test-Path $pad) { ... }.' }),
  ps({ cmd: 'Get-FileHash bestand.zip -Algorithm SHA256', label: 'Controlegetal van een bestand', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Get-Acl . | Format-List', label: 'Rechten van deze map', tags: ['bestanden'] }),
  ps({ cmd: 'Select-String -Path *.txt -Pattern \'zoekterm\'', label: 'Zoeken in bestanden', tags: ['zoeken'], template: true,
    note: 'Voeg -Recurse toe voor submappen, -CaseSensitive als hoofdletters moeten kloppen, -SimpleMatch om regex uit te zetten.' }),
  ps({ cmd: 'Select-String -Path *.log -Pattern \'error\' -Recurse', label: 'Fouten zoeken in logbestanden', tags: ['zoeken'] }),
  ps({ cmd: 'Compress-Archive -Path ".\\*" -DestinationPath archief.zip', label: 'Map inpakken als zip', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Expand-Archive -Path archief.zip -DestinationPath .\\uitgepakt', label: 'Zip uitpakken', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Get-ChildItem | Sort-Object Length -Descending | Select-Object -First 15 Name, Length',
    label: 'Grootste bestanden in deze map', tags: ['bestanden'] }),

  // ── Navigeren ─────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-Location', label: 'Huidige map', tags: ['bestanden'] }),
  ps({ cmd: 'Set-Location C:\\pad', label: 'Naar een andere map', tags: ['bestanden'], template: true,
    note: 'In CommandDeck pakt cd / Set-Location de werkmap zelf, zodat de volgende opdracht daar blijft.' }),
  ps({ cmd: 'Set-Location ~', label: 'Naar de gebruikersmap', tags: ['bestanden'] }),
  ps({ cmd: 'Push-Location; Set-Location C:\\pad', label: 'Tijdelijk naar een andere map', tags: ['bestanden'], template: true,
    note: 'Pop-Location gaat terug naar waar je was.' }),
  ps({ cmd: 'Pop-Location', label: 'Terug naar de vorige map', tags: ['bestanden'] }),
  ps({ cmd: 'Get-PSDrive', label: 'Schijven en powershell-drives', tags: ['bestanden'],
    note: 'Naast C: ook Env, HKCU, HKLM, Variable. Get-ChildItem Env: toont omgevingsvariabelen.' }),

  // ── Processen ─────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-Process', label: 'Draaiende processen', tags: ['systeem'] }),
  ps({ cmd: 'Get-Process | Sort-Object CPU -Descending | Select-Object -First 15',
    label: 'Processen met de meeste CPU', tags: ['systeem'] }),
  ps({ cmd: 'Get-Process | Sort-Object WorkingSet -Descending | Select-Object -First 15 Name, Id, WorkingSet',
    label: 'Processen met het meeste geheugen', tags: ['systeem'] }),
  ps({ cmd: 'Get-Process | Where-Object { $_.ProcessName -like \'*chrome*\' }',
    label: 'Zoeken in draaiende processen', tags: ['systeem'], template: true }),
  ps({ cmd: 'Stop-Process -Name notepad', label: 'Programma afsluiten op naam', tags: ['systeem'], template: true, danger: true,
    note: 'Sluit alle processen met die naam. Voeg -Force toe als het niet wil.' }),
  ps({ cmd: 'Stop-Process -Id 1234', label: 'Proces afsluiten op id', tags: ['systeem'], template: true, danger: true,
    note: 'Het proces stopt meteen. Verkeerd pid: kijk eerst met Get-Process welke id je bedoelt.' }),
  ps({ cmd: 'Start-Process notepad', label: 'Programma starten', tags: ['systeem'], template: true }),
  ps({ cmd: 'Start-Process powershell -Verb RunAs', label: 'PowerShell als beheerder starten', tags: ['systeem'],
    note: 'Opent een nieuw venster met een UAC-vraag. Werkt niet \'in\' dit venster.' }),

  // ── Diensten ──────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-Service', label: 'Windows-diensten', tags: ['systeem'] }),
  ps({ cmd: 'Get-Service | Where-Object { $_.Status -eq \'Running\' }', label: 'Alleen draaiende diensten', tags: ['systeem'] }),
  ps({ cmd: 'Get-Service | Where-Object { $_.Status -eq \'Stopped\' }', label: 'Gestopte diensten', tags: ['systeem'] }),
  ps({ cmd: 'Get-Service -Name spooler', label: 'Eén dienst opzoeken', tags: ['systeem'], template: true }),
  ps({ cmd: 'Restart-Service -Name spooler', label: 'Dienst herstarten', tags: ['systeem'], template: true, danger: true,
    note: 'Vereist vaak beheerdersrechten. Stop-Service / Start-Service kan ook apart.' }),
  ps({ cmd: 'Stop-Service -Name spooler', label: 'Dienst stoppen', tags: ['systeem'], template: true, danger: true,
    note: 'Vereist vaak beheerdersrechten. Een dienst die andere dingen nodig hebben, start daarna niet vanzelf weer.' }),
  ps({ cmd: 'Start-Service -Name spooler', label: 'Dienst starten', tags: ['systeem'], template: true }),

  // ── Netwerk ───────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-NetIPAddress', label: 'IP-adressen van deze pc', tags: ['netwerk'] }),
  ps({ cmd: 'Get-NetAdapter', label: 'Netwerkadapters', tags: ['netwerk'] }),
  ps({ cmd: 'Get-NetTCPConnection -State Listen | Select-Object LocalAddress, LocalPort, OwningProcess',
    label: 'Poorten waarop iets luistert', tags: ['netwerk'],
    note: 'OwningProcess is het pid; koppel dat met Get-Process -Id.' }),
  ps({ cmd: 'Get-NetTCPConnection -State Listen | Where-Object { $_.LocalPort -eq 8080 }',
    label: 'Wie luistert op deze poort?', tags: ['netwerk'], template: true }),
  ps({ cmd: 'Test-NetConnection google.com', label: 'Verbinding testen', tags: ['netwerk'],
    note: 'Ping plus route. Voor een poort: Test-NetConnection google.com -Port 443.' }),
  ps({ cmd: 'Test-NetConnection google.com -Port 443', label: 'Poort op een server testen', tags: ['netwerk'], template: true }),
  ps({ cmd: 'Resolve-DnsName domein.nl', label: 'DNS-gegevens opvragen', tags: ['netwerk'], template: true }),
  ps({ cmd: 'Get-DnsClientCache', label: 'DNS-cache tonen', tags: ['netwerk'] }),
  ps({ cmd: 'Clear-DnsClientCache', label: 'DNS-cache legen', tags: ['netwerk'] }),
  ps({ cmd: 'Get-NetRoute | Where-Object { $_.DestinationPrefix -eq \'0.0.0.0/0\' }',
    label: 'Standaardgateway', tags: ['netwerk'] }),
  ps({ cmd: '(Invoke-WebRequest -Uri https://api.ipify.org -UseBasicParsing).Content',
    label: 'Openbaar IP-adres', tags: ['netwerk'] }),
  ps({ cmd: '1..254 | ForEach-Object { $ip = "192.168.1.$_"; if (Test-Connection $ip -Count 1 -Quiet -ErrorAction SilentlyContinue) { $ip } }',
    label: 'Welke hosts in 192.168.1.x reageren', tags: ['netwerk'], template: true,
    note: 'Pas het netwerk aan. Duurt even: 254 pings achter elkaar.' }),
  ps({ cmd: '(netsh wlan show profiles) | Select-String "All User Profile"',
    label: 'Opgeslagen wifinamen', tags: ['netwerk'],
    note: 'netsh wlan show profiles staat ook bij cmd. Dit filtert meteen op de namen.' }),

  // ── Systeem ───────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-ComputerInfo | Select-Object CsName, WindowsProductName, WindowsVersion, OsBuildNumber, CsTotalPhysicalMemory',
    label: 'Korte systeemgegevens', tags: ['systeem'],
    note: 'Get-ComputerInfo zonder Select-Object is een lang rapport. Duurt een paar seconden.' }),
  ps({ cmd: 'Get-CimInstance Win32_OperatingSystem | Select-Object Caption, Version, LastBootUpTime, FreePhysicalMemory',
    label: 'Windows-versie en laatste start', tags: ['systeem'] }),
  ps({ cmd: 'Get-CimInstance Win32_LogicalDisk | Select-Object DeviceID, VolumeName, @{N=\'VrijGB\';E={[math]::Round($_.FreeSpace/1GB,1)}}, @{N=\'TotaalGB\';E={[math]::Round($_.Size/1GB,1)}}',
    label: 'Vrije ruimte per schijf', tags: ['systeem'] }),
  ps({ cmd: 'Get-HotFix | Sort-Object InstalledOn -Descending | Select-Object -First 15',
    label: 'Laatste Windows-updates', tags: ['systeem'] }),
  ps({ cmd: 'Get-Date', label: 'Datum en tijd', tags: ['systeem'] }),
  ps({ cmd: '$PSVersionTable', label: 'PowerShell-versie', tags: ['systeem'] }),
  ps({ cmd: 'Get-Host', label: 'Hostgegevens van deze powershell', tags: ['systeem'] }),
  ps({ cmd: 'Get-ExecutionPolicy -List', label: 'Execution policy per niveau', tags: ['systeem'],
    note: 'Bepaalt of .ps1-bestanden mogen draaien. Voor jezelf: Set-ExecutionPolicy -Scope CurrentUser RemoteSigned.' }),
  ps({ cmd: 'Set-ExecutionPolicy -Scope CurrentUser RemoteSigned', label: 'Scripts toestaan voor deze gebruiker', tags: ['systeem'], template: true,
    note: 'RemoteSigned: eigen scripts mogen, gedownloade moeten ondertekend zijn. Geen beheerder nodig.' }),
  ps({ cmd: 'Get-LocalUser', label: 'Lokale gebruikers', tags: ['systeem'] }),
  ps({ cmd: 'Restart-Computer', label: 'Pc opnieuw opstarten', tags: ['systeem'], danger: true,
    note: 'Voeg -Force toe om open programma\'s niet te vragen. Stop-Computer sluit af.' }),
  ps({ cmd: 'Stop-Computer', label: 'Pc afsluiten', tags: ['systeem'], danger: true,
    note: 'Sluit Windows af. Voeg -Force toe om open programma\'s niet te vragen. Dit venster gaat dan ook dicht.' }),

  // ── Omgeving ──────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-ChildItem Env:', label: 'Alle omgevingsvariabelen', tags: ['prompt'] }),
  ps({ cmd: '$env:PATH -split \';\'', label: 'PATH regel voor regel', tags: ['prompt'] }),
  ps({ cmd: '$env:Path = [System.Environment]::GetEnvironmentVariable(\'Path\',\'Machine\') + \';\' + [System.Environment]::GetEnvironmentVariable(\'Path\',\'User\')',
    label: 'PATH van Windows opnieuw inlezen', tags: ['prompt'],
    note: 'Machine + User in één regel. CommandDeck leest PATH zelf ook opnieuw bij elke opdracht, zodat nieuwe tools niet vragen om herstarten.' }),
  ps({ cmd: '$env:USERNAME', label: 'Huidige gebruiker', tags: ['prompt'] }),
  ps({ cmd: '[Environment]::GetFolderPath(\'Desktop\')', label: 'Pad naar het bureaublad', tags: ['prompt'] }),
  ps({ cmd: 'Get-Clipboard', label: 'Tekst van het klembord', tags: ['prompt'] }),
  ps({ cmd: 'Get-Clipboard | Out-File "$env:USERPROFILE\\Desktop\\klembord.txt" -Encoding utf8',
    label: 'Klembord naar een bestand op het bureaublad', tags: ['prompt'],
    note: 'Schrijft naar je bureaublad. C:\\klembord.txt mag Windows meestal niet aanraken zonder beheerder.' }),
  ps({ cmd: 'Set-Clipboard -Value \'tekst\'', label: 'Tekst op het klembord zetten', tags: ['prompt'], template: true }),
  ps({ cmd: 'Get-History', label: 'Commando\'s van deze sessie', tags: ['prompt'],
    note: 'Elke opdracht is een nieuwe powershell. Plak je meerdere regels in één keer, dan is dát wél één sessie — variabelen en pipes blijven daarin heel.' }),

  // ── Uitvoer vormen ────────────────────────────────────────────────────────
  ps({ cmd: 'Get-ChildItem | Format-Table Name, Length, LastWriteTime -AutoSize',
    label: 'Tabelweergave', tags: ['prompt'] }),
  ps({ cmd: 'Get-Process | Format-List *', label: 'Alle eigenschappen van processen', tags: ['prompt'],
    note: 'Format-List * toont ook velden die Format-Table weglaat. Werkt achter elk Get-* commando.' }),
  ps({ cmd: 'Get-Process | Out-GridView', label: 'Resultaat in een filterbaar venster', tags: ['prompt'],
    note: 'Opent een Windows-tabel waar je in kunt zoeken. Alleen op een desktop, niet in deze uitvoer.' }),
  ps({ cmd: 'Get-ChildItem | ConvertTo-Json', label: 'Als JSON tonen', tags: ['prompt'] }),
  ps({ cmd: 'Get-ChildItem | Export-Csv -Path lijst.csv -NoTypeInformation',
    label: 'Naar CSV exporteren', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Import-Csv lijst.csv', label: 'CSV inlezen', tags: ['bestanden'], template: true }),
  ps({ cmd: 'Get-ChildItem | Where-Object { $_.Length -gt 1MB }',
    label: 'Bestanden groter dan 1 MB', tags: ['bestanden'] }),
  ps({ cmd: 'Get-ChildItem $env:USERPROFILE -Recurse -File -ErrorAction SilentlyContinue | Where-Object { $_.Length -gt 500MB } | Select-Object FullName, @{N=\'MB\';E={[math]::Round($_.Length/1MB,1)}}',
    label: 'Bestanden groter dan 500 MB in je profiel', tags: ['bestanden'],
    note: 'C:\\ zelf vraagt beheerder en duurt lang. Dit zoekt onder je gebruikersmap.' }),
  ps({ cmd: 'Remove-Item "$env:TEMP\\*" -Recurse -Force -ErrorAction SilentlyContinue',
    label: 'Tijdelijke bestanden legen', tags: ['bestanden'], danger: true,
    note: 'Bestanden die in gebruik zijn blijven staan. Geen prullenbak.' }),
  ps({ cmd: '-join ((33..126) | Get-Random -Count 16 | ForEach-Object { [char]$_ })',
    label: 'Willekeurig wachtwoord van 16 tekens', tags: ['prompt'] }),
  ps({ cmd: 'Get-ChildItem | Group-Object Extension | Sort-Object Count -Descending',
    label: 'Bestanden groeperen op extensie', tags: ['bestanden'] }),
  ps({ cmd: 'Get-ChildItem -Recurse -File | Measure-Object -Property Length -Sum',
    label: 'Totale grootte van deze map', tags: ['bestanden'] }),

  // ── Hulp ──────────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-Help Get-ChildItem -Full', label: 'Uitleg bij een cmdlet', tags: ['prompt'], template: true,
    note: 'Eerste keer: Update-Help (liefst als beheerder) zodat de teksten binnenkomen.' }),
  ps({ cmd: 'Get-Command *net*', label: 'Cmdlet zoeken op naam', tags: ['prompt'], template: true }),
  ps({ cmd: 'Get-Alias', label: 'Alle aliassen (dir, cd, ls, …)', tags: ['prompt'],
    note: 'dir, ls en cd werken in powershell omdat het aliassen zijn. Get-Alias dir laat zien waar dir op wijst.' }),
  ps({ cmd: 'Get-ChildItem | Get-Member', label: 'Welke eigenschappen heeft dit object?', tags: ['prompt'],
    note: 'Het kernidee van powershell: uitvoer is objecten, geen tekst. Get-Member toont wat je erna kunt vragen.' }),
  ps({ cmd: 'Get-Module -ListAvailable', label: 'Beschikbare modules', tags: ['prompt'] }),

  // ── Gebeurtenissen ────────────────────────────────────────────────────────
  ps({ cmd: 'Get-WinEvent -LogName System -MaxEvents 20', label: 'Laatste systeemgebeurtenissen', tags: ['systeem'] }),
  ps({ cmd: 'Get-WinEvent -FilterHashtable @{LogName=\'Application\'; Level=2} -MaxEvents 20',
    label: 'Laatste toepassingsfouten', tags: ['systeem'],
    note: 'Level 2 is Error. 3 is Warning, 4 is Information.' }),

  // ── Register ──────────────────────────────────────────────────────────────
  ps({ cmd: 'Get-ItemProperty HKCU:\\Software', label: 'Registerwaarden onder HKCU\\Software', tags: ['systeem'], template: true,
    note: 'Powershell-drives HKCU: en HKLM:. Pas op met Set-ItemProperty — een verkeerde sleutel raakt Windows.' }),
  ps({ cmd: 'Get-ChildItem HKCU:\\Software | Select-Object Name', label: 'Registermappen onder HKCU\\Software', tags: ['systeem'] }),

  // ── Bouwstenen voor .ps1 ──────────────────────────────────────────────────
  ps({ cmd: '$ErrorActionPreference = \'Stop\'', label: 'Stoppen bij de eerste fout', tags: ['powershell'], snippet: true,
    note: 'Zet dit bovenaan een script. Standaard gaat powershell bij veel fouten gewoon door.' }),
  ps({ cmd: 'param(\r\n  [Parameter(Mandatory)]\r\n  [string]$Pad\r\n)', label: 'Verplicht argument op een script', tags: ['powershell'], snippet: true,
    note: 'Komt als eerste in het bestand, nog vóór andere code. Aanroepen: .\\script.ps1 -Pad C:\\werk.' }),
  ps({ cmd: 'try {\r\n  # werk\r\n} catch {\r\n  Write-Error $_\r\n}', label: 'Fouten opvangen', tags: ['powershell'], snippet: true }),
  ps({ cmd: 'foreach ($f in Get-ChildItem -File) {\r\n  $f.Name\r\n}', label: 'Lus over bestanden', tags: ['powershell'], snippet: true }),
  ps({ cmd: 'if (Test-Path $pad) {\r\n  Write-Output "bestaat"\r\n} else {\r\n  Write-Output "ontbreekt"\r\n}', label: 'Bestaat dit pad? (script)', tags: ['powershell'], snippet: true }),
  ps({ cmd: 'Write-Output $waarde | Out-File -FilePath log.txt -Append -Encoding utf8',
    label: 'Naar een logbestand schrijven', tags: ['powershell'], snippet: true }),
]

module.exports = { PS_COMMANDS }
